project:
  type: website
  output-dir: docs

website:
  title: "Sarah Bauerle Danzman"
  navbar:
    background: secondary
    search: true
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - pubs.qmd


format:
  html:
    theme:
      - flatly
 #     - brand
    css: styles.css
    toc: true
    page-layout: full

editor: visual

