project:
  type: website
  output-dir: docs

website:
  title: "Sarah Bauerle Danzman"
  cookie-consent: true
  page-footer: "Â© 2025, Sarah Bauerle Danzman"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - about.qmd
      - research.qmd
      - policy.qmd
      - teaching.qmd
      - leadership.qmd
      - tools.qmd
    right:
      - icon: envelope
        href: mailto:sbauerle@iu.edu
      - icon: linkedin
        href: https://www.linkedin.com/in/sarah-bauerle-danzman/
      - text: "{{< fa brands square-bluesky >}}"        
        href: https://bsky.app/profile/sarahbauerled.bsky.social
      - icon: github
        href: https://github.com

format:
  html:
    theme:
      - flatly
 #     - brand
    css: styles.css
    include-in-header:
      - text: |
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
          <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    toc: true
    page-layout: full

editor: visual

